version: "3.7"

services:
  support-api:
    build: .
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    environment:
      NODE_PATH: .
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_HOST: ${POSTGRES_HOST}
      DB_PORT: ${POSTGRES_PORT}
    volumes:
      - "/node_modules_support:/app/node_modules"
      - "$PWD:/app"
  support-postgres:
    container_name: support-postgres
    hostname: support-postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - "support-postgres:/var/lib/postgresql"

volumes:
  support-postgres:
    external: true
  node_modules_office:
    external: true